apiVersion: v2
name: external-secrets
description: External Secrets umbrella chart
type: application
version: 1.0.0
appVersion: "1.3.1"

dependencies:
  - name: external-secrets # External Secrets Operator
    version: 1.3.1
    repository: https://charts.external-secrets.io
  - name: connect # 1Password Connect
    version: 2.2.1
    repository: https://1password.github.io/connect-helm-charts